# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a1AGv9hIJ7p6Kvh9bkUgn7huK2dwX0Kb
"""

!pip install spacy
!python -m spacy download en_core_web_sm

# Install spaCy and download the language model
!pip install spacy
!python -m spacy download en_core_web_sm

# Import spaCy
import spacy

# Load the spaCy model for English
nlp = spacy.load("en_core_web_sm")

# Input sentence
sentence = "Natural Language Processing is fascinating and has diverse applications."

# Process the sentence using spaCy NLP pipeline
doc = nlp(sentence)

# Remove stopwords and perform lemmatization
processed_tokens = [
    token.lemma_.lower() for token in doc if not token.is_stop and token.is_alpha
]

# Display the results
print("Original Sentence:", sentence)
print("Processed Tokens:", processed_tokens)